[package]
name = "mdbook-compile-output"
version = "0.1.0"
edition = "2024"

[dependencies]
mdbook = "0.4"
serde_json = "1.0.140"
strip-ansi-escapes = "0.1"

[[bin]]
name = "mdbook-compile-output"
path = "src/main.rs"
